### ISSUE TITLE
Suggestions for configuration

### ISSUE THREAD

**Issue by Bodyash** [cliffniff/media-controls#1]
Hi,

Extension works perfectly, thanks for you job, it's amazing!

Noticed that there is no way to change position (Like Openweather extension)
![image](https://user-images.githubusercontent.com/2454569/131194394-ab5588f6-e37e-4762-a4dd-b65c7c85af2d.png)

Also there is no way to completely hide track name, if set to 0 - there is still "|...|" on the panel

**Comment by cliffniff** [comment]
I was planning to add those features soon. They will be most likely in the next update which won't take long. Thanks for trying it out!

**Comment by cliffniff** [comment]
All of the options you requested were added in the latest realease. So I will close this now.
