### ISSUE TITLE
Debug log spam when no player is active

### ISSUE THREAD

**Issue by TIS-Arne** [cliffniff/media-controls#10]
When no player is active I get debug log spam in the system journal with messages like this one:

"Attempting to remove actor of type 'StButton' from group of class 'StBoxLayout', but the container is not the actor's parent."

**Comment by cliffniff** [comment]
Can you post the exact steps so I can replicate the issue?

**Comment by cliffniff** [comment]
Found the bug, I will fix it in the next update. The fixes are all ready in the repo.

**Comment by cliffniff** [comment]
Fixed it in the latest release!
