### ISSUE TITLE
Add spacing around name for bubble selection

### ISSUE THREAD

**Issue by jacksongoode** [cliffniff/media-controls#13]
I think there ought to be a little bit of padding on either side so that the edge of the selection bubble isn't against the text.
![image](https://user-images.githubusercontent.com/54308792/132264930-5eec649d-24ff-482d-8297-2f0035ea7940.png)

**Comment by cliffniff** [comment]
It never came into my consideration, selection styles in my theme are different. I tested it on two themes(Material and Pop theme). I will add them however . Thanks for the report.
