### ISSUE TITLE
Suggestion: Track title order

### ISSUE THREAD

**Issue by svaldivia2** [cliffniff/media-controls#14]
It would be nice to be able to change the order of the track title ... now it follows the syntax "song_title - author" and was trying to swap it to "author - song_title"

Maybe modifying this tab setting a bit
![2021-09-10 00;49;17  Screenshot](https://user-images.githubusercontent.com/6644649/132797207-c82b784a-d277-448f-91a5-dcbf44794970.png)

Thanks!

**Comment by cliffniff** [comment]
Added it in the latest release. Thanks for the suggestion!
