### ISSUE TITLE
V17 | Padding Issue

### ISSUE THREAD

**Issue by mBilG** [cliffniff/media-controls#16]
Thanks for the amazing extension.

Just updated to the latest version (17).
Noticed 2 issues with padding (issue not present in previous version):

1. Player icons are too small (probably due to larger padding).
2. Title appears to be bottom-aligned: text gets cut-off when letters go below the line (g/y/q/p etc).

I'm using a different shell theme. However, even if i change to adwaita, the buttons still appear smaller than the rest of the icons.

**Comment by cliffniff** [comment]
Thanks for reporting the issue.
Can you send me a screenshot and the name of your theme? I tested it on Pop theme, Materia theme, Orchis theme and the White Sur theme but the issue didn't exist.

**Comment by cliffniff** [comment]
Hi, I figured out the issue and fixed it. 
To apply the fix you can use this command, `cd ~/.local/share/gnome-shell/extensions/mediacontrols@cliffniff.github.com/ && curl -OL https://raw.githubusercontent.com/cliffniff/media-controls/main/player.js`

**Comment by mBilG** [comment]
I'm currently using Fluent_compact theme by Vinceliuice.
I set my panel size to 26 px.
The icons appear bigger now, but still tiny compared to other icons (and previous version)

This is before applying fix:
![image](https://user-images.githubusercontent.com/63431684/133356641-f6d1dbd0-42a6-4f9a-a544-69bf2a09f819.png)

This is after fix mentioned above:
![image](https://user-images.githubusercontent.com/63431684/133355751-405c6ad6-1e3e-40c2-a0c6-a2cf71e34c00.png)

This is from v14:
![image](https://user-images.githubusercontent.com/63431684/133356058-c477710b-8928-4b60-8d37-02ac80bd61d2.png)

Maybe you need to remove top and bottom paddings/margins and let the theme control that?

**Comment by cliffniff** [comment]
> Maybe you need to remove top and bottom paddings/margins and let the theme control that?

Yes, that's what I did. In v14, all the elements were on the panel on their own. Now they are in a separate container. I'll find a workaround for this.

**Comment by cliffniff** [comment]
![image](https://user-images.githubusercontent.com/53598550/133359197-3fd62c83-b925-4cb6-8a73-3da3b173ca74.png)
![image](https://user-images.githubusercontent.com/53598550/133359268-8b9736a9-bd93-4e0d-9e1d-33e27ef5f2ce.png)
I installed the theme and tested it on my machine and it shows the icons fine.

**Comment by mBilG** [comment]
I found a fix:

I use this for the buttons' style:

style: "padding: 0px 2px; margin: 0px 2px;"

Here's the result:
![image](https://user-images.githubusercontent.com/63431684/133360354-339e65c5-3751-40fe-b2f2-f7288f00b43f.png)

**Comment by cliffniff** [comment]
I think it is a issue specific to the theme. The weird thing is it looks fine in the same theme when I installed it.

**Comment by mBilG** [comment]
> Yes, that's what I did. In v14, all the elements were on the panel on their own. Now they are in a separate container. I'll find a workaround for this.

Maybe the padding/margin of the container also needs to be adjusted?

I also noticed that the player icon has the same bug. I don't usually use the icon though, so i disabled it.

Just tested, I think the issue is caused when using "Just perfection" extension and setting my panel size to lower than 30px.

Panel 26px:
![image](https://user-images.githubusercontent.com/63431684/133362975-8928018b-3291-4d06-968b-a34a05ab7d86.png)

Panel 32px:
![image](https://user-images.githubusercontent.com/63431684/133363099-4030e86b-c812-494c-b675-de9d35f96c13.png)

**Comment by cliffniff** [comment]
Fixed the bug properly. Rerun the command `cd ~/.local/share/gnome-shell/extensions/mediacontrols@cliffniff.github.com/ && curl -OL https://raw.githubusercontent.com/cliffniff/media-controls/main/player.js` to apply it. Thanks for reporting!

**Comment by mBilG** [comment]
Excellent.. Works like a charm..
Thanks for your help and for the great extension.. keep it up..
