### ISSUE TITLE
Strange graphical bug

### ISSUE THREAD

**Issue by philibertc** [cliffniff/media-controls#18]
![image](https://user-images.githubusercontent.com/57588282/133456090-fb9da3f2-5764-4623-9b03-692bec87e519.png)
![image](https://user-images.githubusercontent.com/57588282/133456104-ce5818f6-7928-4eb2-a515-ed2e63c7462b.png)

No bug on previous release.

**Comment by philibertc** [comment]
Better after executing `cd ~/.local/share/gnome-shell/extensions/mediacontrols@cliffniff.github.com/ && curl -OL https://raw.githubusercontent.com/cliffniff/media-controls/main/player.js` :
![image](https://user-images.githubusercontent.com/57588282/133458899-4a53599c-41ca-458d-8445-0f0b60a40ddc.png)
But there is still the problem.

**Comment by cliffniff** [comment]
This was reported before in #16. Let's continue the issue there. And also what is the name of your theme?

**Comment by philibertc** [comment]
Hello, my shell theme is Orchis-dark-compact.
There is no issue with default gnome theme and the non "compact" version of my theme.

**Comment by cliffniff** [comment]
Thanks I will look into it straight away!

**Comment by philibertc** [comment]
Okay. Thanks for your awesome extension and your prompt investigation!

**Comment by philibertc** [comment]
> Also have you changed the panel size?

This is what the compact version of my theme does, it refines the panel.

**Comment by cliffniff** [comment]
Can you try re-running the command now. It should be fixed now. 
`cd ~/.local/share/gnome-shell/extensions/mediacontrols@cliffniff.github.com/ && curl -OL https://raw.githubusercontent.com/cliffniff/media-controls/main/player.js`

**Comment by philibertc** [comment]
Hmm, no:
![image](https://user-images.githubusercontent.com/57588282/133470868-69759783-354b-45e2-972f-cdd59a3e6eb3.png)

**Comment by cliffniff** [comment]
Did you try restarting the shell or relogging in?

**Comment by philibertc** [comment]
Restart shell only.

**Comment by cliffniff** [comment]
Sorry need to update the command. Here you go, `cd ~/.local/share/gnome-shell/extensions/mediacontrols@cliffniff.github.com/ && curl -OL https://raw.githubusercontent.com/cliffniff/media-controls/main/player.js && curl -OL https://raw.githubusercontent.com/cliffniff/media-controls/main/stylesheet.css`

**Comment by philibertc** [comment]
Solved! Thanks!

**Comment by cliffniff** [comment]
No problem!
