### ISSUE TITLE
Setting is not accessible

### ISSUE THREAD

**Issue by MoonMarcher** [cliffniff/media-controls#19]
`The settings of extension mediacontrols@cliffniff.github.com had an error:
```
SyntaxError: expected expression, got '?'
```

Stack trace:
```
_init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:204:33
OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:132:13
run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:175:20
main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
run@resource:///org/gnome/gjs/modules/script/package.js:222:19
start@resource:///org/gnome/gjs/modules/script/package.js:206:5
@/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
````

**Comment by cliffniff** [comment]
Can you give me more details on how you got this error? What exactly you did before this happened and any settings you changed before this happened.

**Comment by MoonMarcher** [comment]
Greetings,
I just installed it fresh from gnome shell extension and as I tried to open settings from tweak tool, I received this error. It shows controls on the top bar in gnome but the settings cannot be opened. I'm using youtube music in brave browser and the player controls are already in the tray.
Best

**Comment by cliffniff** [comment]
Thanks for reporting this. Have you tried re-logging in?

**Comment by MoonMarcher** [comment]
Yes, I tried restart and re-login. Didn't work.

**Comment by cliffniff** [comment]
Can you provide a screenshot of the error?

**Comment by MoonMarcher** [comment]
This is the window which pops up instead of settings.

![Media_control_error](https://user-images.githubusercontent.com/67588213/133784804-a3f41223-8024-48d3-88aa-bafd86c5b262.png)

**Comment by cliffniff** [comment]
> `The settings of extension [mediacontrols@cliffniff.github.com](mailto:mediacontrols@cliffniff.github.com) had an error:
> 
> ```
> SyntaxError: expected expression, got '?'
> ```
> 
> Stack trace:
> 
> ```
> _init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:204:33
> OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
> asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:132:13
> run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:175:20
> main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
> run@resource:///org/gnome/gjs/modules/script/package.js:222:19
> start@resource:///org/gnome/gjs/modules/script/package.js:206:5
> @/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
> ```

From what you have shown here, It doesn't seem to be a problem with the extension. Can you try removing the extension, loggin in and installing it again.

**Comment by MoonMarcher** [comment]
I tried. It didn't help. The very same error pops up.

**Comment by cliffniff** [comment]
Very strange. Could be another extension is conflicting.

**Comment by MoonMarcher** [comment]
Yeah, that's a strong guess. Here's my current extensions in use.

![Screenshot from 2021-09-17 15-04-55](https://user-images.githubusercontent.com/67588213/133787182-7d259eba-6bb3-4f69-a07c-82e9a41b4640.png)

**Comment by cliffniff** [comment]
I'll test it with those extensions installed. Can you tell me your Gnome version and the distro.

**Comment by MoonMarcher** [comment]
Great. Here's the information:

Ubuntu 20.04.3 LTS
GNOME Version 3.36.8

**Comment by MoonMarcher** [comment]
Thanks for the info.
