### ISSUE TITLE
Feature request: hide media player controls from notification panel

### ISSUE THREAD

**Issue by n1c0saurio** [cliffniff/media-controls#20]
First of all, nice extension!

May be useful having an option to hide the controls shows in notifications, so you don't have that functionality duplicated.

**Comment by cliffniff** [comment]
Nice idea. I will add it.

**Comment by cliffniff** [comment]
Added in https://github.com/cliffniff/media-controls/commit/28a83cb3a1d8167e73fbf85e7b329d99daf1564d.
