### ISSUE TITLE
Bug: Media Controls still show after song finishes

### ISSUE THREAD

**Issue by Voperak** [cliffniff/media-controls#21]
The controls don't disappear even after a song ends and no song is played after.

You might want to add a timer to make the controls disappear if a song finishes (isn't paused or stopped) and no song is played in the next 10 (or however many you want) seconds.

**Comment by cliffniff** [comment]
The extension only disappears when the player disconnects from the DBus. What was the media player you were using? Could be something specific to the player.

**Comment by Voperak** [comment]
I guess I should have made the title "feature request". I am suggesting that it should disappear while there isn't any music playing, or at least have an option to do so.

**Comment by Voperak** [comment]
It does not for me. It may be an issue with Manjaro Gnome. However, a button would fix any possible issues in the future people may have due to their setups . Thanks!
