### ISSUE TITLE
Local Files Artwork Not Showing

### ISSUE THREAD

**Issue by Avijneyam** [cliffniff/media-controls#23]

**Comment by cliffniff** [comment]
Hello, please provide more details on the issue.

**Comment by Avijneyam** [comment]
> Hello, please provide more details on the issue.

while playing locally downloaded songs via Spotify... Artwork not showing of that song in Open Track And Information Menu

**Comment by cliffniff** [comment]
Thanks for reporting the issue. I will look into it.

**Comment by Avijneyam** [comment]
> Thanks for reporting the issue. I will look into it.

i added screenshot links

**Comment by cliffniff** [comment]
Thanks

**Comment by cliffniff** [comment]
The extension behaves the way it is intended to. If you are offline there is no way for the extension to load the artwork. Spotify  is using their own caching system, so they cache the artwork when downloading the song. You need to play the song when you are online at least one time, so extension can cache the artwork. I hope you understands, thank you.
