### ISSUE TITLE
Blacklisted media still showing 

### ISSUE THREAD

**Issue by devanshvarmaa** [cliffniff/media-controls#24]
Amazing extension chief
however blacklisting is not working for some reason 
I blacklisted Mozilla Firefox, and YouTube. But it is still showing up in the player

**Comment by cliffniff** [comment]
Since you have not replied, I will close the issue.

**Comment by adekmaulana** [comment]
i had the same problem, i blacklisted Google Chrome but it's still there, or i did it wrong.

![Screenshot from 2021-11-11 20-50-44](https://user-images.githubusercontent.com/25561256/141309485-684a0d3a-8acf-45d6-84e1-fc17f7c5eb33.png)

**Comment by cliffniff** [comment]
> i had the same problem, i blacklisted Google Chrome but it's still there, or i did it wrong.
> 
> ![Screenshot from 2021-11-11 20-50-44](https://user-images.githubusercontent.com/25561256/141309485-684a0d3a-8acf-45d6-84e1-fc17f7c5eb33.png)

The extension does not check for the name of the executable, instead it checks for the name in the desktop file. So just "chrome" should work.

**Comment by adekmaulana** [comment]
> > i had the same problem, i blacklisted Google Chrome but it's still there, or i did it wrong.
> > ![Screenshot from 2021-11-11 20-50-44](https://user-images.githubusercontent.com/25561256/141309485-684a0d3a-8acf-45d6-84e1-fc17f7c5eb33.png)
> 
> The extension does not check for the name of the executable, instead it checks for the name in the desktop file. So just "chrome" should work.

Thanks, now it's working

**Comment by jh0l** [comment]
Is there a way to put examples and instructions for using the "blacklist" feature on documentation or on the extension homepage somewhere? Having to search through the github issues for a main feature is kind of inconvenient

**Comment by venkivijay** [comment]
@cliffniff  What would be the blacklist string for "Microsoft Teams" application? Name in the .desktop file is `Microsoft Teams - Preview`. Player display name is `Microsoft Teams Notification`. Executable name is `teams`. None of the above worked for me.
