### ISSUE TITLE
Spotify album artwork not showing correctly

### ISSUE THREAD

**Issue by lorenzobazzana** [cliffniff/media-controls#27]
First things first, this extension is a godsend, nice work!

I noticed that the track information menu won't show at all album artwork for Spotify songs if the option "Cache images" is turned off.
If said option is turned on, it will show the correct artwork only if it has already been downloaded before, meaning that if a song with a new artwork is playing it won't show the right image unless I click on the play/pause button inside the track info menu (it appears that clicking does a refresh of the image).

Lastly, the media icon for Spotify doesn't seem to be working correctly, it shows a generic gray rectangle with two notes inside instead of the Spotify icon. This seems to be related just to that player, because Firefox shows up right.

**Comment by lorenzobazzana** [comment]
I'm using GNOME 40.4 on Fedora 34. The extension version is 17 and the extensions app version is 41.0. There doesn't seem to be any errors in the extension app.

**Comment by cliffniff** [comment]
Try running `rm home/$HOME/.config/media-controls/` and reinstalling the extension.

**Comment by cliffniff** [comment]
What is the output of `ls ~/.config/ | grep media-controls?

**Comment by lorenzobazzana** [comment]
Nothing again. Could it be a problem with Spotify?

**Comment by lorenzobazzana** [comment]
No, it's not. Toggling offline mode on and off doesn't change anything either

**Comment by cliffniff** [comment]
This issue seems specific to you. I could not figure out what the culprit was. I will close this issue for now, if the issue still exists in the next update feel free to reopen.

**Comment by Dal78** [comment]
This seems to be happening to me.
fresh install endevourOS downloaded from extentions.gnome site.
Spotify is the flatpack if that matters
