### ISSUE TITLE
Different results when I try to raise the source app.

### ISSUE THREAD

**Issue by canbeardig** [cliffniff/media-controls#38]
So I assign left click to raise player action but I am having different results with different apps on GNOME 40.5

- VLC works as intended.
- For Rhythmbox and Firefox, clicking doesn't raise the app but gives a notification that the app is ready.
- For Spotify (AUR) clicking doesn't give any results.

**Comment by cliffniff** [comment]
This is because spotify doesn't not support many common MPRIS commands. Many open-source apps works properly, but obviously we can't do anything about spotify. There is a workaround though, it takes some work to implement, how ever I will look into it.

**Comment by canbeardig** [comment]
Thanks for the explanation.
