### ISSUE TITLE
Cover not full height

### ISSUE THREAD

**Issue by SIMULATAN** [cliffniff/media-controls#44]
All of the covers of my spotify songs aren't full size but rather very small.
This doesn't seem to be caused by a specific song because it's happening with all songs I previously tried.

Screenshot:
![Small Album Art](https://user-images.githubusercontent.com/63104422/144707425-a8cd0a33-03dd-4660-a58b-4b599af4ebec.png)

**Comment by VeteraNovis** [comment]
I'm experiencing the same issue. Does this still happen to you?

**Comment by ChrisLauinger77** [comment]
It does not happen to me. What is the setting Max widget width ?

**Comment by ChrisLauinger77** [comment]
![grafik](https://github.com/cliffniff/media-controls/assets/3518684/08da5f00-950b-4919-8e34-a92d782948a4)
not reproducible

**Comment by ChrisLauinger77** [comment]
seems same as #65
