### ISSUE TITLE
Spotify flatpak bugs

### ISSUE THREAD

**Issue by patrickaldis** [cliffniff/media-controls#49]
I'm having a few problems at the moment using the extension with the flatpak version of spotify:
- The icon is not displayed correctly (the default audio icon is displayed)
- Clicking on album artwork in the detailed view doesn't open the player
Screenshot below:

![Screenshot from 2021-12-26 09-21-43](https://user-images.githubusercontent.com/46719614/147404022-a0453960-c2a3-419f-99b1-ffe12044e12b.png)

**Comment by UdittLamba** [comment]
same issues here

**Comment by ChrisLauinger77** [comment]
Icon part is same as #47

**Comment by cliffniff** [comment]
> Icon part is same as #47 Clicking the album art does also not open the player in none-flatpak case. Seems like its not implemented that way. @cliffniff Is clicking the album art supposed to open the player ?

It's not supposed to do that.

**Comment by ChrisLauinger77** [comment]
Bug is covered in #47 - closing it as duplicate
