### ISSUE TITLE
Duplication bug with Museeks

### ISSUE THREAD

**Issue by martin-desktops** [cliffniff/media-controls#51]
Hello to all of you!
I came across the following media source duplication bug during using Museeks player—except the actual song name there is also a “Museeks” source, which is totally useless.

Ubuntu 21.10
media-controls v20
Museeks  0.12.0

Regards, Martin.

![image](https://user-images.githubusercontent.com/64419373/148824719-bdec9f04-7403-445a-80ff-820d8b023863.png)

**Comment by ChrisLauinger77** [comment]
Might be a bug in museeks. It does not happen for VLC, Spotify, Firefox Youtube, Rythmbox
