### ISSUE TITLE
[Feature request] Fine-tune padding control

### ISSUE THREAD

**Issue by mindctrlSE** [cliffniff/media-controls#52]
Greetings!
I was wondering if it would be possible to add padding control for each element (i.e., player icon, track title, control icons etc.) and also padding to other extensions in the top bar? For example, this is how my extension looks like:

![padding](https://user-images.githubusercontent.com/82389560/148970335-e607a1f6-36d1-4029-a03a-10027df20773.png)
Here I would like to reduce the padding to the left of the extension and reduce the player icon padding.

Thank you for this awesome extension!

**Comment by ChrisLauinger77** [comment]
#68 also asks about padding

**Comment by ChrisLauinger77** [comment]
Should be controlled by the theme IMHO and not be the extension.
@cliffniff what is your opionon ?
