### ISSUE TITLE
Change the music icon or the player icon 

### ISSUE THREAD

**Issue by tanaybhomia** [cliffniff/media-controls#55]
I am using spotify web app from edge and it appears that you cannot change the music icon or the player icon that is, It would be nice if we could add and change the icon also the icon that is default does not match with the icons that the shell is using so,

**Comment by ChrisLauinger77** [comment]
Could be related to #47

**Comment by ChrisLauinger77** [comment]
When I use Spotify web app in firefox I get:
![grafik](https://github.com/cliffniff/media-controls/assets/3518684/6ea2fbd1-42b8-45d2-be34-9d5d3c02c0fa)

I think its correct. It plays in firefox.
Maybe attach a screenshot how it looks for you. I suggest using a native linux browser. (just for spotify listening).
Or the spotify app itself.

**Comment by ChrisLauinger77** [comment]
#47 #49
