### ISSUE TITLE
Separators missaligned  

### ISSUE THREAD

**Issue by tanaybhomia** [cliffniff/media-controls#56]
The seperators are not aligned properly and It seems that the left one is a bit down while the right one is a bit up and wise a versa also I love the work that you have done, I was finding something like this for a long time.

BTW here is the glance of it, I have also installed the extension from the Github itself and not from the gnome extensions center and I have also ran the script that you have mentioned in the Readme. 

Here is the photo 
![image](https://user-images.githubusercontent.com/71910027/151476673-5faee4d9-765f-4f4a-bcd5-d6cea3cc70c7.png)
As you can se the left one is a bit down and the right one is a bit on the upper side.

**Comment by skligys** [comment]
I had the same problem and fixed it by editing CSS style here https://github.com/cliffniff/media-controls/blob/0b7c83612e729692dcebd09bb0dce605a54afa0c/player.js#L96 to
```
style: "padding: 0px 3px 0px 0px; margin: 0px auto;",
```

**Comment by ChrisLauinger77** [comment]
Also fixed in main d804df90a6761ad8d1e2ae6263ee475bd95a13ce
