### ISSUE TITLE
Track Information Window is Off-Centre

### ISSUE THREAD

**Issue by tonymartino** [cliffniff/media-controls#62]
Hello,

I've noticed that the track information window's contents are not quite centred:
![Media Controls Screenshot](https://user-images.githubusercontent.com/65514761/193333394-70e87aa4-9868-4b34-9b96-bae244a8347b.png)

**Comment by radiden** [comment]
Same here, my album artwork is also really small, but that might be a Spotify running in flatpak issue
![image](https://user-images.githubusercontent.com/28237353/193656210-8265eece-3b6c-4a32-821c-562f6b2b28d6.png)

- GNOME 42.4 on Wayland
- Fedora Workstation 36

**Comment by felbsn** [comment]
Same but i don't think that caused by media provider because issue persist even if no image available, also padding fix given in readme not solving this. 

* gnome 42.5
* pop_os 22.04

**Comment by CodeWizardPixel** [comment]
![image](https://github.com/cliffniff/media-controls/assets/75926277/d25b8d77-9f98-4dca-82ba-42d147794fd2)
Same problem

- pop_os 22.04
- gnome 42.5

**Comment by sergiotca** [comment]
![image](https://github.com/cliffniff/media-controls/assets/41351896/c64dc4b2-4bd5-46d8-9d93-b17648470a18)

Issue persists on gnome 44.2 & X11 (Fedora 38)

**Comment by ChrisLauinger77** [comment]
Same as #87
