### ISSUE TITLE
GNOME 43 "The extension is incompatible with the current GNOME version" fix.

### ISSUE THREAD

**Issue by InnocentZero** [cliffniff/media-controls#63]
When updating to gnome 43, gnome's extension manager displays `The extension is incompatible with the current GNOME version`. To fix this, navigate to `~/.local/share/gnome-shell/extensions/gTile@vibou/metadata.json` and add 43 in the list of shell versions.

```json
"shell-version": [
    "43"
  ],
```

This fixes the compatibility issue and the extension works as intended.

**Comment by bbbenji** [comment]
For me it was: `~/.local/share/gnome-shell/extensions/mediacontrols@cliffniff.github.com/metadata.json`

**Comment by TheKrafter** [comment]
Yeah, we just need an update where the extension is marked as 43-compatible

**Comment by cliffniff** [comment]
Merged #78
