### ISSUE TITLE
Track information no longer updates in GNOME 43 after resuming from sleep

### ISSUE THREAD

**Issue by bengiff** [cliffniff/media-controls#66]
I recently updated to Fedora 37 with GNOME 43, and I edited the metadata.json file to manually get this extension working again. It seemed to work fine, but after suspending my PC and then resuming work, the track information displayed has not updated. I closed and reopened my player and toggled the extension off and on. These caused the extension to get the correct track information initially, but it still does not change when a new track starts playing.

**Comment by ChrisLauinger77** [comment]
I just tested resume from sleep in debian testing gnome 44- it works there.
I even put it to sleep while music was playing and it played on resume again.
Everything was updated when the song changed. So I doubt its a bug in the extension.
