### ISSUE TITLE
Controls not appearing after log out/in with Spotify open

### ISSUE THREAD

**Issue by ctgrubb** [cliffniff/media-controls#7]
If I have Spotify open and log out (either from inactivity or intentionally) and then log back in, the artist/title and controls do not appear. Same behavior if music is paused or actively playing. I'm using Pop 20.04, Gnome 3.36.8, and Spotify 1.1.55.498 (from snap), if it matters.

**Comment by cliffniff** [comment]
The extension only supports Gnome 3.38 and 40 only. I haven't tested it on 3.36, but I can help you to get it to work. For more context, did you install the extension from the Github releases or the extensions.gnome.org website? And also see if there are any errors in the extensions app and provide them. Thanks for replying!

**Comment by ctgrubb** [comment]
Ah my bad I somehow didn't notice it was only 3.38 and 40. I installed via extensions.gnome.org, and I have not encountered any errors in the extensions app. It seems to work perfectly in 3.36.8 except for this issue, granted I've only been using for an hour or two.

**Comment by cliffniff** [comment]
Okay, I'll try to replicate the issue on Gnome 3.36 when I have some free time.
Until then, if you can perform these steps and post the results.

- In the terminal enter `journalctl -f -o cat /usr/bin/gnome-shell` and keep it open.
- Try to replicate you issue (locking the system and unlocking it)
- Post the output of the terminal

**Comment by cliffniff** [comment]
Since I was unable to replicate the issue and there is no reply from you, I will close this issue.
