### ISSUE TITLE
[Feature Request] Track information menu can have seek bar?

### ISSUE THREAD

**Issue by HubKing** [cliffniff/media-controls#72]
I have set up left clicking to show track information pop-up, because basically I want something like Android's notification area music controller. Android has added seek bar to it since Android 10. I wonder if the  track information could also so music seek bar.

Android Music notification

![image](https://user-images.githubusercontent.com/10900489/218292419-eba6e473-daa8-482b-a28e-e03c318e3106.png)

Proposed feature

![image](https://user-images.githubusercontent.com/10900489/218292659-f8d67c01-b935-45e7-b149-bfb92c36cb58.png)

**Comment by ChrisLauinger77** [comment]
see #33
