### ISSUE TITLE
[Feature Request] Toggle instead of open, for  "track information menu"

### ISSUE THREAD

**Issue by HubKing** [cliffniff/media-controls#75]
In settings -> Other, if I assign "open  track information menu" to a mouse action, such as left click, and do that action to show the track information and do the action again, it re-opens the track information. I think a more sensible behaviour would be just closing the track information when it is already opened.

That is, I think "Toggle  track information menu" makes more sense, because I don't think anyone would want to re-open it when it is already opened.

**Comment by NaiveInvestigator** [comment]
I agree too, this is expected behaviour.

is there any updates on this FR?

**Comment by ChrisLauinger77** [comment]
Currently it does what it says - it opens it.

**Comment by ChrisLauinger77** [comment]
@cliffniff looks like the settings are named "open" but they actually toggle.
`                toggle_menu: _("Open sources menu"),
                toggle_info: _("Open track information menu"),`

**Comment by ChrisLauinger77** [comment]
Fixed in main and gnome44
