### ISSUE TITLE
Feature request: Alignment of controls and text.

### ISSUE THREAD

**Issue by jenschurchill** [cliffniff/media-controls#8]
Hi,

Great work so far.

I wonder, if we could get a "Controls to the left" feature?

I have placed your extension in the upper left corner, and in this configuration it would be better to have "Icon | Controls | Information" rather than "Icon | Information | Controls".

As the information is of variable length, this would make certain the controls don't move, when the information changes.

Further, if one were to place this to the right of the screen, "Information (text-aligned right) | Icon | Controls" might be preferable?

And last, in a center placement, a fixed width option might make sense with the information either being clipped or scrolling in the available space?

**Comment by cliffniff** [comment]
Thanks for replying. This looks like a great idea, I will add it in the next update. Cheers!

**Comment by cliffniff** [comment]
Added it in the latest release!
