### ISSUE TITLE
Issue with track title while playing local file via vlc

### ISSUE THREAD

**Issue by kaash04** [cliffniff/media-controls#80]
![Screenshot from 2023-05-06 20-14-21](https://user-images.githubusercontent.com/112819097/236631500-9956fcec-44ce-4548-83cc-fb7b79613cd2.png)
while playing a local file in vlc media player, it converts "spaces" in its name to "%20".

**Comment by ChrisLauinger77** [comment]
works for me
![grafik](https://github.com/cliffniff/media-controls/assets/3518684/bcab7826-3a3c-454c-a0ce-efce596460cc)
might be a problem of the file itself
