### ISSUE TITLE
Explain: "Options > Blacklist Players" please - also need a "Stop" button

### ISSUE THREAD

**Issue by rizlaw** [cliffniff/media-controls#81]
I see no explanation how to use this feature, although it would appear to be self-evident. You enter the player you want to blacklist and hit the "+" sign. The problem is it doesn't work that why from what I can tell.

So how do you blacklist "vlc" and "firefox" from being automatically picked up by this extension and controlled?
If this feature is broken it should be fix or removed and at the very least a short explanation on how to use it would be nice.

Also, the extension needs a "stop" button to control those players that still use a "stop" button like Audacious and DeadBeef. "Stop" is important when outputting to ALSA directly.

**Comment by ChrisLauinger77** [comment]
The blacklist is fixed with #90 - but this is only for gnome 45.
The stop button would be a new feature.

**Comment by ChrisLauinger77** [comment]
@cliffniff for the stop button request - I do not think it is really nec. most of the players to not have it.
I have the feeling it would result in more issues - what are your thoughts about the stop button ?

**Comment by cliffniff** [comment]
> I meanwhile also fixed the blacklist in branch gnome44. But its not updated on E.G.O. - @cliffniff do you also plan to upload/release the version from branch gnome44 ? It would give debian (gnome43) and other distros which are not on gnome45 soon also some fixes / translation / new settings dialog. Also the caching which requires soup3 (https://gjs.guide/extensions/upgrading/gnome-shell-43.html#soup3) is changed in this branch (see #85) .

Yeah, I will publish a release for gnome 44. The 45 release is still being reviewed.

**Comment by cliffniff** [comment]
> @cliffniff for the stop button request - I do not think it is really nec. most of the players to not have it. I have the feeling it would result in more issues - what are your thoughts about the stop button ?

I agree it is not necessary, if more users request this feature we can add it as opt-in, what do you think?

**Comment by ChrisLauinger77** [comment]
I think it will cause more harm then it would help.
Closing it

**Comment by ChrisLauinger77** [comment]
@cliffniff I found a list of all unreviewed extensions:
https://extensions.gnome.org/review/
