### ISSUE TITLE
controls are invisible on Ubuntu 22.04

### ISSUE THREAD

**Issue by shmu26** [cliffniff/media-controls#82]
I have the extension installed and I can access the settings. When I change the position to the left or to the right I can see the date shifting position slightly, but the controls are invisible. 
The visibility settings are at default.
![Screenshot-1](https://github.com/cliffniff/media-controls/assets/13636596/b7ea834b-ec59-46c0-ba63-8bf9d6c33a27)

**Comment by shmu26** [comment]
My bad... the controls will display when a media player is active!

**Comment by hbonnavaud** [comment]
Hi, same probleme here. @shmu26, what do you mean by "a media player is active"?
I oppened for example rythmbox to test but the extension seams to have no effect, the gnome top bar elements move when I move the extension position but it still seams to be a transparent square in my top bar. What am I missing?
