### ISSUE TITLE
JS ERROR: TypeError: Soup.SessionAsync is not a constructor

### ISSUE THREAD

**Issue by Spurlos** [cliffniff/media-controls#85]
During playback (spotify) i get these warnings in gnome-shell log, usually on song switching during a playlist.

```
JS ERROR: TypeError: Soup.SessionAsync is not a constructor
getRequest/<@/home/spurlos/.local/share/gnome-shell/extensions/mediacontrols@cliffniff.github.com/utils.js:57:24
getRequest@/home/spurlos/.local/share/gnome-shell/extensions/mediacontrols@cliffniff.github.com/utils.js:56:12
_saveImage@/home/spurlos/.local/share/gnome-shell/extensions/mediacontrols@cliffniff.github.com/player.js:750:54
_playerPropsChanged@/home/spurlos/.local/share/gnome-shell/extensions/mediacontrols@cliffniff.github.com/player.js:325:26
```

**Comment by ChrisLauinger77** [comment]
debian testing- gnome 44.5 - does not happen to me

**Comment by ChrisLauinger77** [comment]
It is related to the soup version @cliffniff 
`Soup.SessionAsync()` is soup 2.x
It seems when you import `import Soup from "gi://Soup";` it takes the newest installed one which is 3.0 (where SessionAsync) was removed.

**Comment by ChrisLauinger77** [comment]
https://lazka.github.io/pgi-docs/Soup-2.4/classes/SessionAsync.html
See the ‘porting guide [libsoup-session-porting]’.
https://libsoup.org/libsoup-2.4/libsoup-session-porting.html

**Comment by ChrisLauinger77** [comment]
I found now this:
https://gjs.guide/extensions/upgrading/gnome-shell-43.html#soup3
And it seems the import for 2.4 does not work any more.

**Comment by ChrisLauinger77** [comment]
ported to soup3

**Comment by ChrisLauinger77** [comment]
@cliffniff I have ported to soup 3 in branch gnome44 and main
the version in branch gnome44 is only for 43 & 44 because gnome 43 started to use soup3 
https://gjs.guide/extensions/upgrading/gnome-shell-43.html#soup3
I think the version for gnome 43 / 44 should also be updated at E.G.O. as caching is broken
