### ISSUE TITLE
[Feature Request] Youtube (Chrome) thumbnail in track information menu

### ISSUE THREAD

**Issue by oliver0700** [cliffniff/media-controls#86]
If you play a song on YouTube, there is no thumbnail in the track information menu visible. It would be nice to see one when opening the menu, similar to what is possible with Spotify.

### Youtube playing music screenshot
![y-screenshot](https://github.com/cliffniff/media-controls/assets/115615311/b309de93-36b9-42ff-b375-de03d896378f)

### Spotify playing music screenshot
![s-screenshot](https://github.com/cliffniff/media-controls/assets/115615311/f97edf3e-54ad-4391-85c3-5b18af2f81d7)

**Comment by vjaykrsna** [comment]
any update on this?
i use youtube music as my default music app
i wish there was thumbnail support for that too

**Comment by ChrisLauinger77** [comment]
I use firefox and I get this:
![grafik](https://github.com/cliffniff/media-controls/assets/3518684/da0f41b4-4f57-4c28-a328-6a1eae860577)

I use chromium I get this:
![grafik](https://github.com/cliffniff/media-controls/assets/3518684/bef3c7fa-77c0-4131-b502-aa6d4bb6b39a)

seems to be browser related not a problem of the extension...
