### ISSUE TITLE
[Feature Request] Track Menu Information Content Not Centered Correctly

### ISSUE THREAD

**Issue by shut696969** [cliffniff/media-controls#87]
Recommend using following CSS attributes for the Track Menu Information box (container of content):

.track_menu_info{
display: flex;
align-items: center;
}

More on flex here: [https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_flexible_box_layout/Aligning_items_in_a_flex_container](url)

I enjoy the extension very much :)

**Comment by ChrisLauinger77** [comment]
added it in Gnome44 branch as well as in Main
