### ISSUE TITLE
mouse action doesn't work when player icon is hidden

### ISSUE THREAD

**Issue by carlwgeorge** [cliffniff/media-controls#9]
If you set `hide-player-icon` to `true` and `mouse-action-left` to `toggle_play`, clicking on the title does nothing.  If you set `hide-player-icon` to `false` then clicking on the title does the expected action.  This is reproducible on both GNOME 3.38.6 (Fedora 33) and GNOME 40.4 (Fedora 34).

**Comment by cliffniff** [comment]
I've tested it and you are correct, mouse actions don't work if any of the elements are hidden. I'll try to fix this issue as soon as possible. I will notify once the fix has been issued. Thanks for reporting this issue!

**Comment by cliffniff** [comment]
It was an easy fix. The fix will be available in the next release, until then you can clone the repo and install from source. Instructions are available [here](https://github.com/cliffniff/media-controls#how-to-install). Again thanks!

**Comment by carlwgeorge** [comment]
Sure thing, thanks for the quick fix.

**Comment by arejula27** [comment]
The real bug is not that it doesn't work, it  is that the left button has the action of the right button

**Comment by cliffniff** [comment]
> The real bug is not that it doesn't work, it is that the left button has the action of the right button

Fixed it in the latest commit.

**Comment by cliffniff** [comment]
Fixed it in the latest release!
