### ISSUE TITLE
[Feature Request] Ability to close the panel window when no media is playing

### ISSUE THREAD

**Issue by Ufuk-a** [cliffniff/media-controls#91]
I use a theme with a floating panel, as in, it has gaps like this:
![image](https://github.com/cliffniff/media-controls/assets/61376126/0945cfa4-8d74-46d8-ad7e-c24b8623f4f7)
However, when no media is playing, rather than disappearing, the panel window just becomes blank. Like this:
![image](https://github.com/cliffniff/media-controls/assets/61376126/70df8e5c-b1d9-49d9-bab1-7b7d34626a74)

Would it be possible to fix this so that it disappears when no media is playing?

**Comment by ChrisLauinger77** [comment]
For me it disappears when all supported not blacklisted players are closed.
Maybe a problem of the theme ?
