### ISSUE TITLE
Title not shown in full in track information panel: scroll rather than clip

### ISSUE THREAD

**Issue by axelsimon** [cliffniff/media-controls#92]
Unless "max widget width" is set 0 to disable it, any long song title will be clipped in the track info panel.

Here are some examples.

200 px:
![Screenshot from 2023-09-15 22-29-04](https://github.com/cliffniff/media-controls/assets/1172256/340c8a44-20f5-4628-a71b-77bbb110a0fb)

500 px (max allowed):
![Screenshot from 2023-09-15 22-29-44](https://github.com/cliffniff/media-controls/assets/1172256/68e89321-16f4-45a3-8607-2cda97687244)

0 px (disabled):
![Screenshot from 2023-09-15 22-28-26](https://github.com/cliffniff/media-controls/assets/1172256/3337571f-1c90-4943-8a94-d06ba169b703)

Clearly, disabling results in an ugly mismatched cover art vs. text.
500 px gets you close, but on a long title it's still clipped
200 px shows you almost nothing of the title ("Long Song Titles A…" vs "Long Song Titles Aren't Cool Anymore Because the Rest of You Fuckers Are No Good at It")

So could the title be scrolled instead of clipped please? :slightly_smiling_face:

**Comment by ChrisLauinger77** [comment]
IMHO scrolling is not what I want. moving stuff is irretating me.
But maybe as an option to enable/disable.
I look into it if this can be done easily in the widget.

**Comment by ChrisLauinger77** [comment]
Same as #58

**Comment by ChrisLauinger77** [comment]
I digged around a little and with css its possible:
https://blog.hubspot.com/website/scrolling-text-css#how-to-create-scrolling-text-css

**Comment by axelsimon** [comment]
Thanks for looking into this, @ChrisLauinger77. 
I'm not sure how irritating scrolling text would be, considering you would only see this if
1. the song title is long
2. you have clicked to open the track info panel.

**Comment by axelsimon** [comment]
Also, #58 is a different issue. It's about scrolling long titles in the taskbar.

This is about scrolling in the track info panel. Please re-open.

**Comment by ChrisLauinger77** [comment]
I found something which I wanna try (I still not like the scrolling).
https://discourse.gnome.org/t/multiline-st-entry-with-wrapping-and-scrollbar/16463
I will try to use wrapping instead of clipping to get multiple lines. Should be OK we have space in the track information panel.
I keep you posted

**Comment by ChrisLauinger77** [comment]
![Bildschirmfoto vom 2023-10-10 19-26-35](https://github.com/cliffniff/media-controls/assets/3518684/d97f4c78-e4ad-4faa-9ca4-bd04e305795e)
This it what it would look like

**Comment by ChrisLauinger77** [comment]
It ready in main branch - gnome45 and later
